### ISSUE TITLE
Encoding error in tests when uploading Spanish language PDF

### ISSUE THREAD

**Issue by palewire** [datadesk/python-documentcloud#111]
It's probably nothing big, but [recent TravisCI tests](https://travis-ci.org/datadesk/python-documentcloud/builds/105318242) have been logging a new encoding error when it tries to upload a Spanish language PDF directly via the API.

Here is [the code that's triggering the error](https://github.com/datadesk/python-documentcloud/blob/master/tests/test_all.py#L437-L440)

``` python
pdf = os.path.join(os.path.dirname(__file__), "español.pdf")
obj = self.private_client.documents.upload(open(pdf, 'rb'))
self.assertTrue(isinstance(obj, Document))
```

Here is the test traceback

```
======================================================================
ERROR: test_private_actions (tests.test_all.DocumentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/datadesk/python-documentcloud/tests/test_all.py", line 439, in test_private_actions
    obj = self.private_client.documents.upload(open(pdf, 'rb'))
  File "/home/travis/build/datadesk/python-documentcloud/documentcloud/toolbox.py", line 53, in _checkcredentials
    return method_func(self, *args, **kwargs)
  File "/home/travis/build/datadesk/python-documentcloud/documentcloud/__init__.py", line 361, in upload
    return self.get(json.loads(response.decode("utf-8"))['id'])
  File "/home/travis/build/datadesk/python-documentcloud/documentcloud/__init__.py", line 272, in get
    data = self.fetch('documents/%s.json' % id).get("document")
  File "/home/travis/build/datadesk/python-documentcloud/documentcloud/__init__.py", line 147, in fetch
    params,
  File "/home/travis/build/datadesk/python-documentcloud/documentcloud/toolbox.py", line 83, in f_retry
    return f(*args, **kwargs)
  File "/home/travis/build/datadesk/python-documentcloud/documentcloud/__init__.py", line 87, in _make_request
    raise e
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 31: ordinal not in range(128)
```

**Comment by palewire** [comment]
The odd thing is these tests had been passing for years and are suddenly failing. Quirk? Something I've done? Change on @knowtheory's end? I dunno.

**Comment by knowtheory** [comment]
Hey @palewire, yeah, we did make a change a couple weeks ago so that slugs could also include unicode characters (we had been stripping them before).  I perhaps had wrongly assumed that because document text could already include unicode if a language required it (including `ñ`, that the change wouldn't require any client side modifications).

We'll take a look at what encoding signaling we can do when handing back JSON files that make clear that the content should be treated as UTF8.

**Comment by palewire** [comment]
I think this has been fixed
