### ISSUE TITLE
Can't access projects (read or create)

### ISSUE THREAD

**Issue by mikejcorey** [datadesk/python-documentcloud#119]
I can access my private documents fine:
```
dc_client = DocumentCloud(settings.DC_USERNAME, settings.DC_PASSWORD)
doc = dc_client.documents.get('3538011-HSBP1017R0023-Other-Border-Wall-RFP-A007')
print doc

# This correctly returns the non-public document:
HSBP1017R0023 Other Border Wall RFP A007
```
... But I can't seem to access my projects at all:
```
project = dc_client.projects.all()

# Returns
Retrying in 2 seconds
Retrying in 4 seconds
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/michael/.envs/border_ownership/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/michael/.envs/border_ownership/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/michael/.envs/border_ownership/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/michael/.envs/border_ownership/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/michael/Documents/CIR/BorderFenceRedux/border_ownership/border_ownership/apps/lawsuits/management/commands/load_documents.py", line 109, in handle
    self.update_document_cloud()
  File "/home/michael/Documents/CIR/BorderFenceRedux/border_ownership/border_ownership/apps/lawsuits/management/commands/load_documents.py", line 34, in update_document_cloud
    project = dc_client.projects.get(id='9922-border-patrol-use-of-force')
  File "/home/michael/.envs/border_ownership/local/lib/python2.7/site-packages/documentcloud/__init__.py", line 457, in get
    hit_list = [i for i in self.all() if str(i.id) == str(id)]
  File "/home/michael/.envs/border_ownership/local/lib/python2.7/site-packages/documentcloud/toolbox.py", line 53, in _checkcredentials
    return method_func(self, *args, **kwargs)
  File "/home/michael/.envs/border_ownership/local/lib/python2.7/site-packages/documentcloud/__init__.py", line 429, in all
    project_list = self.fetch('projects.json').get("projects")
  File "/home/michael/.envs/border_ownership/local/lib/python2.7/site-packages/documentcloud/__init__.py", line 147, in fetch
    params,
  File "/home/michael/.envs/border_ownership/local/lib/python2.7/site-packages/documentcloud/toolbox.py", line 83, in f_retry
    return f(*args, **kwargs)
  File "/home/michael/.envs/border_ownership/local/lib/python2.7/site-packages/documentcloud/__init__.py", line 87, in _make_request
    raise e
urllib2.HTTPError: HTTP Error 500: Internal Server Error
```

This seems to happen with anything involving projects: I also can't create them.

I suppose it's possible this is related to https://github.com/documentcloud/documentcloud/issues/411, but this happens whether I try to access the client with or without credentials.

**Comment by mikejcorey** [comment]
This appears to have been an internal DocumentCloud issue with projects, which @knowtheory has now fixed.

**Comment by palewire** [comment]
Glad to hear it got sorted out.

**Comment by knowtheory** [comment]
Yep, looks like there were a handful of older projects that had null titles, and that was causing the API to bomb out.

Cleared out all the nils, so it shouldn't crop up again.
