### ISSUE TITLE
Python 3.6 error

### ISSUE THREAD

**Issue by palewire** [datadesk/python-documentcloud#123]
```
======================================================================
ERROR: test_private_actions (tests.test_all.DocumentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/datadesk/python-documentcloud/tests/test_all.py", line 339, in test_private_actions
    obj.put()
  File "/home/travis/build/datadesk/python-documentcloud/documentcloud/__init__.py", line 678, in put
    self._connection.put('documents/%s.json' % self.id, params)
  File "/home/travis/build/datadesk/python-documentcloud/documentcloud/toolbox.py", line 53, in _checkcredentials
    return method_func(self, *args, **kwargs)
  File "/home/travis/build/datadesk/python-documentcloud/documentcloud/__init__.py", line 135, in put
    params.encode("utf-8"),
  File "/home/travis/build/datadesk/python-documentcloud/documentcloud/toolbox.py", line 83, in f_retry
    return f(*args, **kwargs)
  File "/home/travis/build/datadesk/python-documentcloud/documentcloud/__init__.py", line 87, in _make_request
    raise e
  File "/home/travis/build/datadesk/python-documentcloud/documentcloud/__init__.py", line 77, in _make_request
    response = request_method(request)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
``

**Comment by palewire** [comment]
I think it was just a problem with the sample document!
