### ISSUE TITLE
[bug] Cannot get full text of some public documents 

### ISSUE THREAD

**Issue by catriuspham** [datadesk/python-documentcloud#125]
DocumentCloud API: https://www.documentcloud.org/api/documents/5758576.json

As you can see from the above URL, this document is public, and we can get its full text via `document.resources.text`.
But when I use `python-documentcloud` to get it, I got this error:

```
NotImplementedError: Currently, DocumentCloud only allows you to access this resource on public documents.
```

Here is the full stack traces:
![screen shot 2019-03-06 at 11 36 43 am](https://user-images.githubusercontent.com/17242255/53856348-25383c00-4004-11e9-962c-bbd0022a23e3.png)

**Comment by palewire** [comment]
Are you sure the document is public? The link you posted doesn't open for me.

![screenshot from 2019-03-06 15-48-11](https://user-images.githubusercontent.com/9993/53921925-42323680-4027-11e9-8681-202480dd3d82.png)

**Comment by catriuspham** [comment]
@palewire Sorry. Could you please try this one instead https://www.documentcloud.org/api/documents/5680384.json?

**Comment by bfeldman89** [comment]
Same issue. 

![Screen Shot 2019-03-09 at 12 38 10 PM](https://user-images.githubusercontent.com/26087892/54075724-3a150980-4268-11e9-9b9c-b690c511cc02.png)

https://www.documentcloud.org/api/documents/5764369.json

**Comment by palewire** [comment]
Thanks for that example. Here's what I see in the public JSON for that document.

```json
{
   "document":{
      "id":"5764369-Hill-v-Madison-County-Complaint",
      "title":"Hill v. Madison County - Complaint",
      "access":"public",
      "pages":12,
      "description":null,
      "source":null,
      "created_at":"Sat, 09 Mar 2019 02:12:37 +0000",
      "updated_at":"Sat, 09 Mar 2019 18:37:32 +0000",
      "canonical_url":"https://www.documentcloud.org/documents/5764369-Hill-v-Madison-County-Complaint.html",
      "language":"eng",
      "file_hash":"8c53f38b3e137d55321492970efde66e4a634746",
      "contributor":"Blake Feldman",
      "contributor_slug":"17279-blake-feldman",
      "contributor_documents_url":"https://www.documentcloud.org/public/search/Account:17279-blake-feldman",
      "contributor_organization":"ACLU of Mississippi",
      "contributor_organization_slug":"aclumississippi",
      "contributor_organization_documents_url":"https://www.documentcloud.org/public/search/Group:aclumississippi",
      "display_language":"eng",
      "resources":{
         "pdf":"https://assets.documentcloud.org/documents/5764369/Hill-v-Madison-County-Complaint.pdf",
         "text":"https://assets.documentcloud.org/documents/5764369/Hill-v-Madison-County-Complaint.txt",
         "thumbnail":"https://assets.documentcloud.org/documents/5764369/pages/Hill-v-Madison-County-Complaint-p1-thumbnail.gif",
         "search":"https://www.documentcloud.org/documents/5764369/search.json?q={query}",
         "print_annotations":"https://www.documentcloud.org/notes/print?docs[]=5764369",
         "translations_url":"https://www.documentcloud.org/translations/{realm}/{language}",
         "page":{
            "image":"https://assets.documentcloud.org/documents/5764369/pages/Hill-v-Madison-County-Complaint-p{page}-{size}.gif",
            "text":"https://www.documentcloud.org/documents/5764369/pages/Hill-v-Madison-County-Complaint-p{page}.txt"
         },
         "published_url":"https://www.documentcloud.org/documents/5764369-Hill-v-Madison-County-Complaint.html"
      },
      "sections":[

      ],
      "data":{
         "type":"complaint",
         "facility":"mcdc"
      },
      "annotations":[

      ]
   }
}```

It looks to me that the call to `self.resources.text` in the source code should work here. If you try that same document again, @bfeldman89, do you still get the error?

**Comment by palewire** [comment]
I just tried it with the wrapper and got the error myself, though the full_text_url that it returns does work. So I suspect the bug must in our decorator intending to limit to access to public documents.

**Comment by bfeldman89** [comment]
@palewire thanks! That works, and it's really not that much trouble for me to just get the text from the `.txt` url.

**Comment by palewire** [comment]
I'll try to get a bug fix out shortly.

**Comment by palewire** [comment]
Wow. I think this is something with urllib. If I run the same code with requests it works.

```python
>>> import urllib.request
>>> req = urllib.request.Request("https://assets.documentcloud.org/documents/5764369/Hill-v-Madison-County-Complaint.txt")
>>> urllib.request.urlopen(req).read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
>>> import requests
>>> requests.get("https://assets.documentcloud.org/documents/5764369/Hill-v-Madison-County-Complaint.txt")
<Response [200]>
```

Anybody have a guess?

**Comment by palewire** [comment]
Wow. If I add a user-agent it works.

```python
req = urllib.request.Request("https://assets.documentcloud.org/documents/5764369/Hill-v-Madison-County-Complaint.txt", headers={'User-Agent' : "Magic Browser"})
```

A bot blocker on the assets subdomain?

**Comment by catriuspham** [comment]
@palewire Thanks for your hard work! It works now.
